In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', 500)

In [3]:
df = pd.read_csv('proof.csv', header=[1], skiprows=[2])

In [6]:
df = df.loc[:,'How old are you in years?': 'Condition']

In [7]:
len(df)

603

In [8]:
df.head()

How old are you in years? What is your gender? - Selected Choice  \
0                         29                                 Female   
1                         30                                   Male   
2                         34                                   Male   
3                         34                                   Male   
4                         29                                   Male   

   What is your gender? - Other - Please specify - Text  \
0                                                NaN      
1                                                NaN      
2                                                NaN      
3                                                NaN      
4                                                NaN      

  I identify my ethnicity as: - Selected Choice  \
0                                     Caucasian   
1                                         Asian   
2                                     Caucasian   
3                                     Caucasian   
4                                     Caucasian   

  I identify my ethnicity as: - Other - Please specify - Text  \
0                                                NaN            
1                                                NaN            
2                                                NaN            
3                                                NaN            
4                                                NaN            

  If someone offers you a drink, are you more likely to ask for:  \
0                                              Water               
1                                              Water               
2                                              Water               
3                                              Water               
4                                    Hoppy microbrew               

  Do you intend to vote in the midterm elections on November 6?  \
0                                                Yes              
1                                                Yes              
2                                                Yes              
3                                              Maybe              
4                                                Yes              

  Did you vote in the 2016 presidential election?  Politically, do you:  \
0                                             Yes         Lean Democrat   
1                                             Yes         Lean Democrat   
2                                             Yes       Lean Republican   
3                                              No  Somewhere in-between   
4                                             Yes         Lean Democrat   

  Are you a registered voter?  Condition  
0                         Yes          1  
1                         Yes          5  
2                         Yes          2  
3                         Yes          1  
4                         Yes          2

All Respondents

In [10]:
conditions = df.groupby('Condition')['Do you intend to vote in the midterm elections on November 6?'].value_counts()

In [11]:
#1 = nelisha
#2 = brandi
#3 = matt
#4 = anthony
#5 = control
conditions

Condition  Do you intend to vote in the midterm elections on November 6?
1          Yes                                                              90
           Maybe                                                            22
           No                                                                9
2          Yes                                                              86
           Maybe                                                            18
           No                                                               17
3          Yes                                                              93
           Maybe                                                            15
           No                                                               13
4          Yes                                                              92
           Maybe                                                            15
           No                                             

In [12]:
from scipy import stats
import numpy as np

In [13]:
voted = np.array([conditions[1].values, conditions[2].values, conditions[3].values, conditions[4].values, conditions[5].values])

In [14]:
voted

array([[90, 22,  9],
       [86, 18, 17],
       [93, 15, 13],
       [92, 15, 13],
       [86, 22, 12]])

In [15]:
stats.chi2_contingency(voted)

(5.703971337053287,
 0.6803519461606464,
 8,
 array([[89.69651741, 18.46102819, 12.84245439],
        [89.69651741, 18.46102819, 12.84245439],
        [89.69651741, 18.46102819, 12.84245439],
        [88.95522388, 18.30845771, 12.73631841],
        [88.95522388, 18.30845771, 12.73631841]]))

34 and under

In [22]:
under_34 = df[df['How old are you in years?']<=34.0]

In [23]:
conditions = under_34.groupby('Condition')['Do you intend to vote in the midterm elections on November 6?'].value_counts()

In [24]:
voted = np.array([conditions[1].values, conditions[2].values, conditions[3].values, conditions[4].values, conditions[5].values])

In [25]:
stats.chi2_contingency(voted)

(8.364553281660275,
 0.3986934159314701,
 8,
 array([[44.        , 14.52      ,  7.48      ],
        [36.66666667, 12.1       ,  6.23333333],
        [38.66666667, 12.76      ,  6.57333333],
        [41.33333333, 13.64      ,  7.02666667],
        [39.33333333, 12.98      ,  6.68666667]]))

Registered Voters Only

In [41]:
registered = df[df['Are you a registered voter?']=='Yes']
conditions = registered.groupby('Condition')['Do you intend to vote in the midterm elections on November 6?'].value_counts()
voted = np.array([conditions[1].values, conditions[2].values, conditions[3].values, conditions[4].values, conditions[5].values])
voted

array([[90, 20,  2],
       [86, 14, 13],
       [91, 11,  3],
       [90, 12,  4],
       [86, 18,  6]])

In [42]:
stats.chi2_contingency(voted)

(17.26664238996481,
 0.027449262096606912,
 8,
 array([[90.87179487, 15.38461538,  5.74358974],
        [91.68315018, 15.52197802,  5.79487179],
        [85.19230769, 14.42307692,  5.38461538],
        [86.003663  , 14.56043956,  5.43589744],
        [89.24908425, 15.10989011,  5.64102564]]))

In [46]:
registered = df[df['Are you a registered voter?']=='Yes']

In [49]:
registered_ct = pd.crosstab(index=registered['Do you intend to vote in the midterm elections on November 6?'],
           columns=registered['Condition'])

In [50]:
registered_ct

Condition                                            1   2   3   4   5
Do you intend to vote in the midterm elections ...                    
Maybe                                               20  14  11  12  18
No                                                   2  13   3   4   6
Yes                                                 90  86  91  90  86

In [52]:
registered_ct.index = ['Maybe', 'No', 'Yes']

In [54]:
stats.chi2_contingency(registered_ct)

(17.26664238996481,
 0.027449262096606912,
 8,
 array([[15.38461538, 15.52197802, 14.42307692, 14.56043956, 15.10989011],
        [ 5.74358974,  5.79487179,  5.38461538,  5.43589744,  5.64102564],
        [90.87179487, 91.68315018, 85.19230769, 86.003663  , 89.24908425]]))

In [56]:
import researchpy as rp

In [57]:
table, results = rp.crosstab(registered['Do you intend to vote in the midterm elections on November 6?'],
                            registered['Condition'], prop='col', test='chi-square')

In [59]:
table

Condition                  \
                                                           1       2       3   
Do you intend to vote in the midterm elections ...                             
Maybe                                                  17.86   12.39   10.48   
No                                                      1.79   11.50    2.86   
Yes                                                    80.36   76.11   86.67   
All                                                   100.00  100.00  100.00   

                                                                            
                                                         4       5     All  
Do you intend to vote in the midterm elections ...                          
Maybe                                                11.32   16.36   13.74  
No                                                    3.77    5.45    5.13  
Yes                                                  84.91   78.18   81.14  
All                                                 100.00  100.00  100.00

In [60]:
results

Chi-square test  results
0  Pearson Chi-square ( 8.0) =   17.2666
1                    p-value =    0.0274
2                 Cramer's V =    0.1257