In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_columns', 500)

In [4]:
df = pd.read_csv('rhml_4_conditions.csv', header=[1], skiprows=[2])

In [5]:
df = df.loc[:,'How many different people we featured in the previous video?': 'Condition']

In [13]:
len(df)

1128

All Respondents

In [6]:
conditions = df.groupby('Condition')['Do you intend to vote in the midterm elections on November 6, 2018?'].value_counts()

In [11]:
#1 = vid_1
#2 = vid_2
#3 = control
conditions

Condition  Do you intend to vote in the midterm elections on November 6, 2018?
1.0        Yes                                                                    274
           Maybe                                                                   41
           No                                                                      35
2.0        Yes                                                                    248
           Maybe                                                                   50
           No                                                                      45
3.0        Yes                                                                    293
           Maybe                                                                   42
           No                                                                      40
Name: Do you intend to vote in the midterm elections on November 6, 2018?, dtype: int64

In [20]:
from scipy import stats
import numpy as np

In [21]:
voted = np.array([conditions[1].values, conditions[2].values, conditions[3].values])

In [22]:
voted

array([[274,  41,  35],
       [248,  50,  45],
       [293,  42,  40]])

In [24]:
stats.chi2_contingency(voted)

(4.600099371055482,
 0.330842727194939,
 4,
 array([[267.08801498,  43.58614232,  39.3258427 ],
        [261.74625468,  42.71441948,  38.53932584],
        [286.16573034,  46.6994382 ,  42.13483146]]))

In [25]:
voted_2 = np.array([[315,35], [298, 45], [335, 40]])

In [27]:
stats.chi2_contingency(voted_2)

(1.8780860119816458,
 0.3910018427896683,
 2,
 array([[310.6741573 ,  39.3258427 ],
        [304.46067416,  38.53932584],
        [332.86516854,  42.13483146]]))

34 and under

In [33]:
under_34 = df[df['How old are you in years?']<=34.0]

In [36]:
condition_34 = under_34.groupby('Condition')['Do you intend to vote in the midterm elections on November 6, 2018?'].value_counts()

In [37]:
voted_34 = np.array([condition_34[1].values, condition_34[2].values, condition_34[3].values])

In [38]:
stats.chi2_contingency(voted_34)

(4.4292394524021255,
 0.35102049860879436,
 4,
 array([[132.74270073,  29.34671533,  24.91058394],
        [124.22445255,  27.46350365,  23.3120438 ],
        [132.03284672,  29.18978102,  24.77737226]]))

25 and under

In [39]:
under_25 = df[df['How old are you in years?']<=25.0]

In [40]:
condition_25 = under_25.groupby('Condition')['Do you intend to vote in the midterm elections on November 6, 2018?'].value_counts()

In [43]:
voted_25 = np.array([condition_25[1].values, condition_25[2].values, condition_25[3].values])

In [44]:
stats.chi2_contingency(voted_25)

(6.498075511934557,
 0.1649116819941333,
 4,
 array([[37.00591716, 12.56804734,  9.4260355 ],
        [38.26035503, 12.99408284,  9.74556213],
        [30.73372781, 10.43786982,  7.82840237]]))

Registered Voters Only

In [49]:
len(registered)

966

In [70]:
registered = df[df['Are you a registered voter?']=='Yes']
conditions = registered.groupby('Condition')['Do you intend to vote in the midterm elections on November 6, 2018?'].value_counts()
voted = np.array([conditions[1].values, conditions[2].values, conditions[3].values])
voted

array([[273,  33,  14],
       [245,  42,  13],
       [292,  40,  14]])

In [71]:
stats.chi2_contingency(voted)

(2.13698793911751,
 0.7105804000621784,
 4,
 array([[268.32298137,  38.0952381 ,  13.58178054],
        [251.55279503,  35.71428571,  12.73291925],
        [290.1242236 ,  41.19047619,  14.68530021]]))

Registered Voters 34 and Under

In [72]:
registered = df[df['Are you a registered voter?']=='Yes']
registered = registered[registered['How old are you in years?']<=34.0]
conditions = registered.groupby('Condition')['Do you intend to vote in the midterm elections on November 6, 2018?'].value_counts()
voted = np.array([conditions[1].values, conditions[2].values, conditions[3].values])
voted

array([[137,  22,  10],
       [112,  24,  11],
       [136,  25,   8]])

In [73]:
stats.chi2_contingency(voted)

(1.8618888809902252,
 0.7611421005324522,
 4,
 array([[134.15463918,  24.74020619,  10.10515464],
        [116.69072165,  21.51958763,   8.78969072],
        [134.15463918,  24.74020619,  10.10515464]]))

Registered and under 25

In [86]:
registered = df[df['Are you a registered voter?']=='Yes']
registered = registered[registered['How old are you in years?']<=25.0]
conditions = registered.groupby('Condition')['Do you intend to vote in the midterm elections on November 6, 2018?'].value_counts()
voted = np.array([conditions[1].values, conditions[2].values, conditions[3].values])
voted

array([[41,  8,  1],
       [30, 13,  6],
       [33,  8,  1]])

In [87]:
stats.chi2_contingency(voted)

(8.7586190656634,
 0.06742431924286127,
 4,
 array([[36.87943262, 10.28368794,  2.83687943],
        [36.14184397, 10.07801418,  2.78014184],
        [30.9787234 ,  8.63829787,  2.38297872]]))